### ISSUE TITLE
Functional tests

### ISSUE THREAD

**Issue by saintsebastian** [peopledoc/layout-linter#10]

**Comment by Pixelik** [comment]
so I'm guessing this means writing tests for each of these functions:

```
scripts/activateTooltips.js
scripts/appendTooltipTo.js
scripts/buildLintedDocument.js
scripts/buildVirtualDom.js
scripts/errorMessagesFor.js
scripts/getBrowserJs.js
scripts/getCss.js
scripts/getLayoutrc.js
scripts/getRootAppFileContents.js
scripts/getRules.js
scripts/getSourceHtml.js
scripts/getTooltips.js
scripts/lintedHtmlWithCssJs.js
index.js
```

maybe `index.js` doesn't need one and maybe more/less tests are needed.. to be discussed..

**Comment by Pixelik** [comment]
_note to self:_

- incorporate babel

**possible tools for minimal setup**
- https://github.com/qunitjs/qunit
- https://github.com/testem/testem
- https://www.npmjs.com/package/proxyquire
- https://github.com/thlorenz/proxyquireify
- https://github.com/browserify/browserify

**more "complete" alternatives**
- https://github.com/rollup/rollup
- https://github.com/gulpjs/gulp
