### ISSUE TITLE
rule: <img> has @alt attribute

### ISSUE THREAD

**Issue by edouard-lopez** [peopledoc/layout-linter#2]
This will help improve accessibility.

Can be either implemented 

### As an instance of [`hasAttributes` rule](https://github.com/peopledoc/pdui-debugger/tree/f53aa4ddb2328f75ebae6da0e2e3575f7e54befc/rules/has-attributes):

```
{
  selector: 'img',
  hasAttributes: 'alt'
}
```
* **pros:**
  * reuse existing rule ;
  * so just config ;
  * can be part of a preset.
* **cons:**
  * up to the user to add it
### By itself

```
{
  selector: 'img',
  imageIsAccessible: true
}
```

* **pros:**
  * allow more complex logic
* **cons:**
  * what does accessible mean? It might lead to a complex rule that overlap with other.

**Comment by Pixelik** [comment]
I think we should just stick to the following set of obvious/intuitive types of **checks**:

```
isTag: '...'
children: [...]
notChildren: [...]
directChildren: [...]
notDirectChildren: [...]
attributes: [...]
notAttributes: [...]
```

and let the users create whatever rules they like with the above and not add extra checks that are basically wrappers of the above checks (like `imageIsAccessible`, `typeIsText`, etc..) and that the dev will have to keep in mind on top of the basic ones.

I think it will be quicker/easier for a dev to write:

```
{
  selector: '.my-image',
  attributes: ['alt', 'attr-2', 'attr-3', 'attr-4']
}
```

than :

```
{
  selector: '.my-image',
  imageIsAccessible: true,
  attributes: ['attr-2', 'attr-3', 'attr-4']
}
```

**Comment by edouard-lopez** [comment]
Thanks for the feedback, as you said they are merely wrappers, moreover that would require people to learn them. While with basic rules we can make is more straightforward to use the tool.
