### ISSUE TITLE
Tweet announcement

### ISSUE THREAD

**Issue by saintsebastian** [peopledoc/layout-linter#51]
Suggestion:
We just released layout-linter, that will analyze your html and create visual feedback for it, based on your own html linting rules!
*add screenshot*

**Comment by Pixelik** [comment]
ping @peopledoc/tribe-js for input

**Comment by xcambar** [comment]
Besides package naming, I think it's a good one. Well done.

**Comment by Pixelik** [comment]
[layout-linter has been published on npmjs](https://www.npmjs.com/package/layout-linter) 🎉  

_(as **layout-linter** after all and **not html-linte**r, html-linter was already taken)_

**Comment by Pixelik** [comment]
I would suggest this tweet:

_**We just released layout-linter on npm, that will lint your html layouts according to your own custom rules!**_

**Comment by Pixelik** [comment]
- plus mention of **CSS selectors** might be important, so smth like:

_We just released layout-linter on npm! It will lint your html layouts according to your own custom rules, using CSS selectors, and provide you with visual feedback: [insert this screenshot: https://raw.githubusercontent.com/peopledoc/layout-linter/master/assets/demo.png]_

?

**Comment by Pixelik** [comment]
@saintsebastian this is ready for tweeting 🙂 
you can tweet it yourself and I'll announce it on our #rd channel if anyone wants to tweet it
what do you think ?

**Comment by Pixelik** [comment]
announced 🙂
